version: "3.1"
services:
  mongodb:
    image: mongo:latest
    container_name: db-parkir-mongo
    volumes:
      - /opt/mongo-data:/data/db
    ports:
      - 27017:27017


  aplikasi:
    container_name: aplikasi-parkir
    image: 0d3ng/springboot-mongo:1.0.0
    depends_on:
      - mongodb
    ports:
      - 8080:8080
