version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    volumes:
      - /opt/mongo-data:/data/db
    ports:
      - 27017:27017
  aplikasi:
    image: 0d3ng/springboot-mongo
    links:
      - mongodb
    ports:
      - 8080:8080