version: "3.1"
services:
  mongo:
    restart: always
    image: mongo:latest
    container_name: springboot-mongo
    volumes:
      - /opt/mongo-data:/data/db
    ports:
      - 27017:27017


  aplikasi:
    build: .
    restart: always
    container_name: springboot
    image: 0d3ng/springboot-mongo
    depends_on:
      - mongo
    ports:
      - 8080:8080
    working_dir: /opt/app
